[package]
name = "test1"
version = "0.1.0"
authors = ["Weixing Sun <weixing.sun@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.probe]
git = "https://github.com/cuviper/rust-libprobe.git"
